### ISSUE TITLE
v.03 test

### ISSUE THREAD

**Issue by freznel10** [joshajohnson/sea-picro#10]
Hi Josh, has v.3 been tested already? Sorry, I could not find the conversations tab hence I placed my question here.

**Comment by joshajohnson** [comment]
Hey Freznel, it''s partially tested.

I've checked all the IO work, but need to check VBUS detection, RGB LED, check a few voltages, and a few other things.
If you can hold off for 48 hours I'll have finished testing and update here with (hopefully) good news.

**Comment by freznel10** [comment]
Thank you!

**Comment by joshajohnson** [comment]
Hi @freznel10,

I assembled a few more boards and tested them, have found two more issues documented in https://github.com/joshajohnson/sea-picro/issues/11. Otherwise everything is working as planned.

Will hopefully resolve by this time tomorrow assuming all goes well.

**Comment by joshajohnson** [comment]
All tested now @freznel10!

I'm ordering a bunch of the 1.0 boards now, so fingers crossed there are no more bugs!

**Comment by freznel10** [comment]
Nice to hear that!:) Hope everything turns out fine for the 1 boards!
