### ISSUE TITLE
0.3 Errata

### ISSUE THREAD

**Issue by joshajohnson** [joshajohnson/sea-picro#11]
- [X] Footprint for D1 is on the small side - update with datasheet / IPC recommended footprint
- [X] Auto reset circuit is not waiting long enough to jump into bootloader on some boards - adjust components to extend charge time.

**Comment by freznel10** [comment]
So entering the bootloader is fine only that it enters the bootloader too early and the reset part does not work?

**Comment by joshajohnson** [comment]
Yes correct - instead of the reset / bootloader point being at 500ms (approx), on one board it's closer to 200ms.
I can still get it to reset, but I just have to tap very quickly.
Should be fairly easy to fix, I just need to swap some parts and take measurements on a few boards to confirm consistent behaviour.

Interestingly I (nor any of the folks testing) have run into this so far, it's just one board on my desk. Maybe I populated a wrong component...

**Comment by joshajohnson** [comment]
Fixed in 64acc074a7ae7dfcb6f1962cd64d2bc71366196c

Reset issue was resolved by moving a cap from 4u7 to 10u in the delay circuit.
