### ISSUE TITLE
Bootloader Mode

### ISSUE THREAD

**Issue by 3rdPhalanx** [joshajohnson/sea-picro#14]
I've been trying to enter the bootloader mode by holding the reset button or shorting the reset and ground pins, and by doing so while shorting or holding reset and connecting it to the computer (Windows 11). I've tried this without a problem on a second sea-picro and it worked successfully. I've found that the sea-picro is detected as an HID/USB but does not appear as a mass storage device. I've tried to uninstall drivers for the device but am not really sure if what I've done is correct.

Any help is appreciated, Thank you

**Comment by joshajohnson** [comment]
Hi, it sounds like the board might be defective as shorting RST whilst plugging the board in should cause it to go into bootloader like on your other board.

You can try shorting the "B" test point on the back of the board to GND whilst plugging it in to bypass the reset circuit, and hopefully with that being held low it'll go into bootloader mode.

Was this a unit you hand assembled or purchased from somewhere?

**Comment by 3rdPhalanx** [comment]
This is 1 of 2 boards that I bought for a sofle build, but I actually already tried the b pin on the back since I already soldered the board on, and was unsuccessful. If it's defective then I'll just contact the seller again thank you

Great board by the way

**Comment by joshajohnson** [comment]
Ah bugger, would have been nice to get it working again.

Out of interest where was the unit purchased from?
All of the units I've sold to vendors have been tested before leaving my bench, so if it's one of those units I'd be keen to get it back and see where the test procedure has failed to allow a faulty board to escape.

**Comment by 3rdPhalanx** [comment]
I ordered it from Beekeeb as a part of a sofle kit.

**Comment by joshajohnson** [comment]
Thanks, that's not a unit I've tested so I'd suggest the best course of action would be reaching out to them and asking for assistance.

**Comment by kamaaina** [comment]
came across this post, and funny thing is, i have the same behavior with *both* of my sea picro's. i bought the ferris sweep kit from beekeeb.  i will try to contact him as well.

like @3rdPhalanx, i soldered my controller to the pcb, but i tried shorting the ground and reset as well as pressing the reset button and both did not work.

**Comment by idank** [comment]
> came across this post, and funny thing is, i have the same behavior with _both_ of my sea picro's. i bought the ferris sweep kit from beekeeb. i will try to contact him as well.
> 
> like @3rdPhalanx, i soldered my controller to the pcb, but i tried shorting the ground and reset as well as pressing the reset button and both did not work.

This sounds like a manufacturing error. I have gone through many sea picros (produced at JLC and Elecrow) and some small percentage of them will either not boot straight from the fab house, or will fail after soldering headers to them, or have a gpio fail, etc etc. I haven't been able to figure out what causes this (it doesn't seem to be a soldering issue on the picro itself), but my understanding is that without a custom test suite at the fab house that checks for specific fault points, this is expected past a certain scale of production.
