### ISSUE TITLE
Prone to shorts with split keyboards?

### ISSUE THREAD

**Issue by idank** [joshajohnson/sea-picro#18]
There's been some talk in discord that the sea picro / RP2040 is prone to shorts when used in split keyboards. Apparently this happens when the TRRS cable between halves is disconnected while the main side is still USB powered. I've personally experienced this once but can't be 100% sure I did exactly that.

Is this a known issue with sea picro, the RP2040 chip, or completely unknown to you?

**Comment by idank** [comment]
p.s. not sure "short" is the correct term here, someone referred to this as hot plugging.

**Comment by joshajohnson** [comment]
I'm not quite sure what you mean.

I understand that plugging / unplugging TRRS cables whilst still connected to USB can cause shorts (as the terminals are all exposed) but that has nothing to do with the selected controller.

Are you saying that if you short out the cable it'll kill one of the controllers? 
If so what side dies and is there any visible damage?

I haven't heard of this issue, or anything similar before so if it's something we can identify and resolve that'd be great.

**Comment by idank** [comment]
No not shorting anything by hand, just plugging / unplugging the trrs cable when USB is connected. Presumably the serial pin on the main side gets killed. This seems specific to sea picro as I've never had this happen on cheap pro micros.

Sadly I don't have the faulty picro anymore. I'll be getting more in a few weeks so I might be able to stress test this.

**Comment by joshajohnson** [comment]
Ah yeah, the serial pin being killed is what you'd expect if you shorted 5V to a 3V3 IO like the RP2040 uses.
This isn't specific to Sea-Picro, it would be common with any microcontroller running at 3V3 (RP2040, STM32, etc).

Assuming it's an IO failure it's not something we'd visually be able to notice, you'd have to de-encapsulate the IC and look at it under a microscope to confirm.

**Comment by idank** [comment]
Seeing as this is pretty common procedure when dealing with split keyboards, is it possible to protect against this within the sea picro?

**Comment by joshajohnson** [comment]
Not really, the simple fix is to unplug the keyboard from power before connecting / disconnecting which is recommend for any controller.

**Comment by idank** [comment]
Roger that, thanks for your work.
