### ISSUE TITLE
5V on pin 25

### ISSUE THREAD

**Issue by idank** [joshajohnson/sea-picro#19]
Hey, not sure if I'm misunderstanding things, but should I be getting 5V between pin 25 and GND? I'm trying to drive the Pimoroni trackball and getting some flaky performance off the 3.3v pin, so I figured I'd try pin 25 but that doesn't seem to work so I must be doing something stupid.

**Comment by joshajohnson** [comment]
Hi, no you should not be getting 5V from this pin - it's a digital output designed for driving LEDs.

You'll want to use the "RAW" pin, as this will provide you with 5V.

**Comment by idank** [comment]
Duh, silly of me! Thanks so much.
