### ISSUE TITLE
D2 alternative?

### ISSUE THREAD

**Issue by idank** [joshajohnson/sea-picro#21]
It seems JLCPCB is always out of the component for D2 (C268294). It's possible to order specific parts for PCBA but figured I'd ask before doing so if there's a suggested alternative one?

**Comment by joshajohnson** [comment]
Any 0603 LED is suitable.

**Comment by idank** [comment]
Thanks.

Looks like Q1,Q2 are out of stock too, is [this](https://jlcpcb.com/parts/compare/111721,516804) a good replacement (right side is BOM)?

**Comment by joshajohnson** [comment]
Yep that looks suitable.
